import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Accordion from 'react-bootstrap/Accordion';

export default function Home() {
  const [tasks, setTasks] = useState(['No Tasks']);
  const [newTask, setNewTask] = useState({
    newTask: ''
  })

  const handleSubmit = (event) => {
    event.preventDefault();
    if (tasks[0] === 'No Tasks') {
      setTasks([newTask.newTask])
      setNewTask({
        newTask: ''
      })
    } else {
      setTasks([...tasks, newTask.newTask])
      setNewTask({
        newTask: ''
      })
    }
  }

  const handleInput = (event) => {
    let name = event.target.name;
    let value = event.target.value;

    setNewTask({ [name]: value })
  }

  const timePlayer = (
    <>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pause" viewBox="0 0 16 16">
  <path d="M6 3.5a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0V4a.5.5 0 0 1 .5-.5zm4 0a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0V4a.5.5 0 0 1 .5-.5z"/>
</svg>

<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-play" viewBox="0 0 16 16">
  <path d="M10.804 8 5 4.633v6.734L10.804 8zm.792-.696a.802.802 0 0 1 0 1.392l-6.363 3.692C4.713 12.69 4 12.345 4 11.692V4.308c0-.653.713-.998 1.233-.696l6.363 3.692z"/>
</svg>
</>
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div>
          <h1>TASKS</h1>
          <form onSubmit={handleSubmit}>
            <input name='newTask' type='text' onChange={handleInput} value={newTask.newTask} />
            <input type='submit' value='ADD TASK' />
          </form>
          <Accordion>
            {
              tasks.map((i, index) => {
                if(i === 'No Tasks') {
                  return (
                  <p>{i}</p>
                  )
                } else {
                return (
                  <Accordion.Item eventKey={index}>
                    <Accordion.Header>{i}</Accordion.Header>
                    <Accordion.Body>
                    
                    {timePlayer}
                    
                    <form>
                      <input type='text' />
                      <input type='submit' value='ADD NOTE' />
                    </form>
                    </Accordion.Body>
                  </Accordion.Item>
                )
                }
              })
            }
          </Accordion>
        </div>

      </main>

    </div>
  )
}
